mysql:
  host: "localhost"
  user: "root"
  password: "root"
  database: "root"

redis:
  host: "localhost"
  port: 6379
  user: "root"
  password: "root"

global-chat:
  enabled: true
  cooldown:
  cooldown-discount:
    vip:
    mvp:

staff-chat:
  prefix: "§7[§cStaffChat§7]"

discord:
  staff-channel-id:
  staff-prefix:
