mysql:
  host: localhost
  user: root
  password: 'root'
  database: root

redis:
  enable: false
  host: localhost
  port: 6379
  user: root
  password: 'root'

global-chat:
  enabled: true
  prefix: '[Global] [%server%] %player% : %message%'
  cooldown:
  cooldown-discount:
    vip:
    mvp:

donator-chat:
  enabled: true
  prefix: '[Donator] [%server%] %player% : %message%'
  cooldown:
  cooldown-discount:
    vip:
    mvp:

staff-chat:
  prefix: '§7[§cStaffChat§7]'

discord:
  token: ''
  staff-channel-id: 000000000000000
  staff-channel-prefix: '[%server%] %prefix%"

message:
  ban-broadcast: "\n&e&l⚡ &cBan Hammer has spoken!\n&7Someone has been sent packing to the \"Banished Realm.\"\n"
  ban-message-issuer:
  ban-message-permanent: "\n&cYou have been banned from the server!\n\n&7Reason: %reason%\n&7Duration: Permanent\n\n&7ID: %id%"
  ban-message-duration: "\n&cYou have been temporarily banned from the server!\n\n&7Reason: %reason%\n&7Ban Expired on: %expire%\n\n&7ID: %id%"

aliases:
  mix:
